/* Greenwich Works — the portal.  The explanations (register AV.5).
   -----------------------------------------------------------------
   Content only.  One entry per thing a first-time reader meets and may
   not know: what it is, when it is due, who sees or approves it, what
   happens if it is late or missing.  Every fact is from the decision
   register or from guide.js; nothing here is invented.  app.js draws
   these as the hover / tap explainer (the small "?" beside a term).

     window.GW_EXPLAIN[key] = { t: title, b: two to four plain sentences }
   ----------------------------------------------------------------- */
window.GW_EXPLAIN = {

  /* ---- the hand-ins, in the order they fall due ---------------------- */
  ethics: { t: "Ethics screening sheet",
    b: "Ten questions your team answers in class at Session 6, straight after its final choice of project, countersigned by your convener; you upload the signed scan. Your convener sets the tier: 1 self-certify, 2 the convener approves, 3 the ethics panel, which sits weekly from 6 October and decides within a week. Nobody collects data or goes out before it is cleared. Due Saturday 17 October." },
  plan: { t: "One-page project plan",
    b: "One page: the question, who it is for, what you will gather, and by when. Due Saturday 24 October, Session 7. Your convener reads it and merges what the marking courses need into the Folio's sections." },
  field: { t: "Field plan (form F1)",
    b: "Where the team is going, when, who with, the area grade and the duty number, signed by your convener. It appears only for teams that tick fieldwork, and nobody goes out without one. Your convener can accept it only once the ethics tier is cleared and the fieldwork gate is open — Monday 5 October at the earliest, and only if the duty phone and the sign-out sheet exist. Due Saturday 17 October, with the ethics sheet. No team does fieldwork until its field plan is approved." },
  charter: { t: "Team charter",
    b: "One page: who does what, how the team decides, and what happens if someone does not deliver. Started at Session 6, due Saturday 7 November with the build. It is the evidence a teacher uses when moving one student up or down from the team mark." },
  folio: { t: "The Folio",
    b: "The one piece of work your team produces between Session 8 and Session 13: about 3,000 words per member plus what the project made. It carries a two-page client brief, a handover page and the AI declaration, and it is not accepted without them. Due Saturday 12 December. Every course marking it takes 5 of the 20 off for each week it is late; nothing is accepted after 15 December." },
  ai: { t: "AI declaration",
    b: "The note filed with the Folio saying what tools you used and what you checked. Using AI is expected; not reading what it gave you is what gets caught, at the viva. Due with the Folio, 12 December; the Folio is not accepted without it." },
  brief: { t: "Client brief (two pages)",
    b: "Two pages written for the body your project reports to, delivered by the team. Part of the Folio, due with it on 12 December; the Folio is not accepted without it." },
  handover: { t: "Handover page",
    b: "One page for next year's team: the data, the methods, and what they should do next. Part of the Folio, due with it on 12 December; the Folio is not accepted without it." },
  lens: { t: "Lens note",
    b: "What a course sets you when it does not mark your team's Folio: about 3,000 words on the same project from that course's angle, same rubric, same 20 marks, plus your viva 10. You never write more than two. Due with the Folio, 12 December; 5 of the 20 off for each week late." },
  viva30: { t: "Viva out of 30",
    b: "From your third lens course on, that course sets you no written piece: it marks your viva out of 30 instead. There is nothing to hand in for it." },
  pcproj: { t: "Project for a course studied as a project",
    b: "About 3,000 words for each course you study as a project, on your own Build Block problem seen through that course. With several such courses you write one joined project and file one file, and have one defence. Due Session 13, 12 December, with the Folio; 5 of the 30 off for each week late." },

  /* ---- the project ---------------------------------------------------- */
  menu: { t: "Project menu",
    b: "What you see from Session 4, 28 September: each project's title, its problem in one line, and who it is for. Teams note the three they like. The full projects follow at Session 5, and the final choice is made at Session 6 with your convener." },
  sequence: { t: "Menu, full projects, then the choice",
    b: "Session 4 (from 28 September): the menu — title, one-line problem, who it is for. Session 5 (from 5 October): the full projects, with the block brief. Session 6 (from 12 October): your team makes its final choice, names itself, seals its prediction with its convener, and answers the ethics sheet in class straight after." },
  twoteams: { t: "At most two teams per project",
    b: "Two teams may take one project, and only on different sites or areas. The portal refuses a third team and refuses a site another team on the same project already holds. If your first choice is full, take one of the other two you noted." },
  patch: { t: "Site or area",
    b: "Where, or on whom, your team works: a neighbourhood, a sample, a sector, a site. It is what makes your study different from the other team on the same project, so the portal refuses a site another team on that project already holds." },
  prediction: { t: "Sealed prediction",
    b: "At Session 6, before any data, your team writes what it expects to find, signs it and seals it with your convener. The convener keeps the envelope and opens it at your team's first viva. It carries no marks. The portal records only that it was sealed, and later opened; never what it says." },
  team_name: { t: "Team name",
    b: "Your team names itself at Session 6, when it makes its final choice. Three to forty characters, and no two teams share a name." },
  choice_state: { t: "Chosen, approved, returned",
    b: "Chosen means your team has entered its choice and your convener has not yet decided. Approved locks it; only your convener can reopen it. Returned means your convener has sent it back with a reason you can read on the team screen — choose again." },
  block: { t: "Build Block",
    b: "A group of courses that share a timetable, and the teams cut from them. There are 19, held by 16 conveners. Your team's project comes from its block, and its block's courses mark it." },
  lane: { t: "Lane",
    b: "Which kind of project a block runs: Client (for a body that asked), Civic (a public question), Venture (something sold, on a University account) or Studio (something made). The lane sets what the team leaves behind and the rules for money and fieldwork." },
  convener: { t: "Convener",
    b: "The person who holds your Build Block. They approve projects and team names, set the ethics tier, sign field plans, log the weekly check, merge the marking courses' needs into the Folio at Session 7, moderate, and read any report a student files. They never enter a mark and never change one. They can waive a late penalty, with a written reason that is logged — so can the office — and that is the one thing they may do to what a mark comes to." },
  tier: { t: "Ethics tier",
    b: "Set by your convener from the ten-question sheet. Tier 1: self-certify, countersigned. Tier 2: the convener approves. Tier 3: the ethics panel, which sits weekly from 6 October and decides within a week: cleared, cleared with conditions, or not cleared. No data is collected before the tier is cleared." },
  gate: { t: "The fieldwork gate",
    b: "Monday 5 October, and only if the duty phone and the sign-out sheet exist by then. No team leaves campus before both exist, whatever its tier. The office opens the gate in the portal; until then no field plan can be accepted." },

  /* ---- the marks ------------------------------------------------------ */
  project30: { t: "The project 30",
    b: "Every course is out of 100 as project 30, mid-term 30, final 40. In an ordinary course the project 30 is the team's Folio 20, moved by up to 3 either way on your viva and the charter, plus your own viva 10. The mid-term and the final stay in the University's own system." },
  regime_folio: { t: "Marks the Folio",
    b: "This course is one of those marking your team's Folio, from its own angle, out of 20. Your project 30 in it is that 20 (±3) plus your viva 10." },
  regime_outside: { t: "Outside Greenwich Works",
    b: "Level 7–8 and postgraduate-programme courses run on the University's ordinary scheme of assessment. No team, no project, nothing to hand in here." },
  project_course: { t: "A course studied as a project",
    b: "A more demanding and more rewarding way to study a subject: one-to-one supervision for an hour every week, a piece of real work of your own on your team's problem seen through that course, and a one-hour oral defence before a panel at the end. Marks: project 30, mid-term 30, oral final 40." },
  midterm: { t: "The mid-term choice",
    b: "In a course studied as a project the teacher chooses the mid-term 30 and states it: a written paper in mid-term week, or the Session 8 plan with the first 1,500 words. It is recorded here; the mark stays in the University's own system." },
  defence: { t: "The oral defence",
    b: "One hour before a panel: the course teacher and a chair named by the Dean; an alumnus may sit as a third member, ask questions, and never scores. Scored out of 40 as command of the subject 15, defends the choices 10, answers the unexpected 10, presents clearly 5. With several joined courses there is one defence and each teacher scores their own course." },
  supervision: { t: "The supervision log",
    b: "One hour a week with your teacher. The teacher ticks each hour held; you confirm it. To sit the defence you need 80 per cent of the hours and a log signed by both of you. Below that the score page is locked unless the office records an exception with a written reason." },
  chair: { t: "The chair",
    b: "Named by the Dean, chairs the defence and does not score. So the chair cannot be the teacher of one of the student's own courses." },
  exception: { t: "Office exception",
    b: "Where a student is below 80 per cent of the supervision hours, the office may record an exception with a written reason, which unlocks that course's score page. It is logged." },
  rubric: { t: "The rubric's five parts",
    b: "Substance 8: the question, the method, and whether the answer is supported. Evidence 4: what was gathered and how honestly it is reported. Integration 3: whether the courses are joined up. Presentation 3: whether a stranger could follow it. Revision 2: that it changed between draft and file. Together 20." },
  adjustment: { t: "The ±3",
    b: "A teacher may move one student up to three marks either way from the team's 20, on the viva and the charter, with a one-line reason. The result stays inside 0 to 20." },
  late: { t: "The late penalty",
    b: "Five of the 20 for every week a hand-in is late, in every course marking it, and five of the 30 for a project-course project; counted from midnight in Karachi on the due day, off the portal's own timestamp. Nothing is accepted after 15 December. A convener or the office may waive it with a written reason." },
  net: { t: "Raw, penalty, net",
    b: "Raw is what the teacher typed. The penalty is worked out by the database from the hand-in's Karachi date. Net is what goes to Examinations. All three are shown, and every change is kept." },
  waiver: { t: "Penalty waived",
    b: "A convener or the office has waived the late penalty, with a written reason that is logged. The mark shows the penalty that was due beside it." },
  moderation: { t: "Moderation",
    b: "The same Folio is marked by up to eight courses. Where their twenties are four marks or more apart the convener samples the Folio and, if they still disagree, orders a re-mark in writing. Nobody but the course teacher changes a mark." },
  marks_visible: { t: "When a mark appears",
    b: "A mark appears on your map once the teacher has submitted it. A draft is not shown. Once the office closes marking for a course, nothing in it can change." },

  /* ---- the rest of the term ------------------------------------------ */
  review: { t: "The Karachi Review",
    b: "Tuesday 15 December, 10:00 to 17:00. Every team exhibits at its own table; a judging pair — a teacher and an alumnus — comes to you for about eight minutes and scores you there. Attendance is compulsory. Nothing is accepted after this day." },
  pvc: { t: "Fifteen minutes with the PVC",
    b: "Dr Naveed is on campus twelve till eight, every day including weekends, 5 October to 12 December. Every team gets two sessions booked automatically; individual slots are first come. Book one day ahead, with one sentence saying what is stuck — the booking is refused without it." },
  claim: { t: "The claim slip and code",
    b: "You are handed a slip with your card carrying your roll number and a one-time code. Your convener tells you when your account opens. Enter both under First time here and choose your own password. Eight wrong codes lock the roll number for an hour; the front desk can issue a new code." },
  report: { t: "Report a teammate",
    b: "It goes to your convener and nobody else; your teammates never see it, and neither does the person you name. It is answered within five working days. Use it in week three, not in December." },

  /* ---- staff ---------------------------------------------------------- */
  marking_card: { t: "The marking card",
    b: "One card per team your course marks. The five rubric lines are the team's 20, entered once. The ±3 and the viva 10 are per student, for the members enrolled in your course. Save a draft as often as you like; submitting puts it in the export, and every change is kept." },
  closing: { t: "Closing marking",
    b: "The office closes a course once its marks are final. After that nothing in it can be changed by anybody; the office can reopen it, with a written reason, which is logged." },
  export: { t: "The export",
    b: "A CSV of your course's project marks: roll, name, raw, penalty, net and the parts. Only the office and the course's own teacher can take it, and every export is logged. Names appear nowhere else on the web." },
  no_marker: { t: "Courses with no marker",
    b: "A course that marks a Folio, or sets a lens note or project, and has no teacher with a portal account: either the Registrar names nobody, or the named teacher has no account yet. Until it is fixed, nobody can enter that course's marks." },
  weekly_check: { t: "The weekly five-question check",
    b: "Once a week from the team's first field visit to Session 13, two minutes each: did you go where the plan says; did anyone go alone; did anything at all happen; is anyone uncomfortable about this site; consent forms — how many, and where are they. Five yes-or-no answers and two lines in the log." },
  ethics_queue: { t: "The ethics queue",
    b: "Teams whose ethics sheet is filed and waiting for a tier, Tier 3 teams to file with the panel, and panel decisions to record. The panel sits weekly from 6 October and decides within a week." },
  board: { t: "The team board",
    b: "One row per team: project, prediction, ethics tier and status, plan, charter, field plan, weekly check, Folio. 'Stuck' is what needs somebody; 'to do' is what waits for you." },
  g_accounts: { t: "Accounts claimed",
    b: "How many of the register have set up their account with the code on their slip. On the day after the slips go out this says whether they worked." },
  g_staff: { t: "Staff on the first password",
    b: "Staff accounts that have not yet chosen their own password. An account on the first password can do nothing but change it." },
  g_storage: { t: "Storage",
    b: "How much of the storage plan the hand-ins have used. The free plan is 1 GB; Supabase Pro from November is what the Folios need. Each file may be 60 MB at most." },
  g_unplaced: { t: "Unplaced",
    b: "Undergraduates who should have a team and have none. Postgraduate programmes, thesis-only students and students who are not registered are not counted." },
  signout: { t: "Sign out, sign in",
    b: "The desk's day sheet, kept in the portal: before a team leaves campus it files where it is going, the grade, who is going and when it is due back — never after 6 pm — and the desk counts heads, sees the cards and the letter, and signs it out. On return the desk signs it in. Two students at least, three anywhere amber; a red site is paper, with the convener's written approval and an escort." },
  f2: { t: "Form F2, the incident form",
    b: "Every incident, near miss, refusal that turned hostile, or approach by anyone in authority is reported to the convener the same day — including the ones where nothing happened. The team writes what happened in its own words; the convener signs; the office records the Registrar's receipt. A site closed after an incident stays closed to every team until the Registrar reopens it." },
  appeal: { t: "Appeal",
    b: "A student who disagrees with a convener's ruling — a removal from the Folio, a team change, a report answered — appeals in writing to the programme heads within seven days. The convener writes an account; the heads decide; their decision ends it. A mark is not appealed here: the University's ordinary route applies." },
  settings: { t: "Settings",
    b: "The dates and switches the rules run on: when the menu, the full projects and the choice open; the fieldwork gate; the late-week rule; when a student sees a mark. Changing one here changes it for everybody, and it is logged." }
};
